export const PERSONS={"1s":"1a persona del singular","2s":"2a persona del singular","3s":"3a persona del singular","1p":"1a persona del plural","2p":"2a persona del plural","3p":"3a persona del plural"};
export const PRONOUNS={"1s":"jo","2s":"tu","3s":"ell/ella/vostè","1p":"nosaltres","2p":"vosaltres","3p":"ells/elles/vostès"};
export const TENSES={present:["Indicatiu","Present"],imperfect:["Indicatiu","Imperfet"],periphrasticPast:["Indicatiu","Passat perifràstic"],simplePast:["Indicatiu","Passat simple"],perfect:["Indicatiu","Perfet"],pluperfect:["Indicatiu","Plusquamperfet"],future:["Indicatiu","Futur"],futurePerfect:["Indicatiu","Futur perfet"],conditional:["Condicional","Condicional"],conditionalPerfect:["Condicional","Condicional perfet"],subjPresent:["Subjuntiu","Present"],subjImperfect:["Subjuntiu","Imperfet"],subjPerfect:["Subjuntiu","Perfet"],subjPluperfect:["Subjuntiu","Plusquamperfet"],imperative:["Imperatiu","Imperatiu afirmatiu"]};
export function normalizeAnswer(s){return s.trim().replace(/\s+/g,' ').toLocaleLowerCase('ca')}
export function isCorrect(input,accepted){const n=normalizeAnswer(input);return accepted.some(x=>normalizeAnswer(x)===n)}
export function fold(s){return s.normalize('NFD').replace(/\p{Diacritic}/gu,'').toLocaleLowerCase('ca')}
export function filterVerbs(verbs,{search='',frequency=100,type='all',favorites=[]}={}){let x=verbs.filter(v=>v.rank<=frequency&&fold(v.infinitive).includes(fold(search)));if(type==='regular')x=x.filter(v=>!v.irregular);if(type==='irregular')x=x.filter(v=>v.irregular);if(type==='favorites')x=x.filter(v=>favorites.includes(v.id));return x.sort((a,b)=>a.infinitive.localeCompare(b.infinitive,'ca'))}
export function candidates(verbs,settings,state,scope={}){let pool=verbs.filter(v=>v.rank<=settings.frequency&&(settings.regular&&!v.irregular||settings.irregular&&v.irregular));if(settings.favoritesOnly)pool=pool.filter(v=>state.favorites.includes(v.id));if(settings.errorsOnly)pool=pool.filter(v=>Object.keys(state.pendingErrors).some(k=>k.startsWith(v.id+'|')));if(scope.verbId)pool=pool.filter(v=>v.id===scope.verbId);const tenses=scope.tense?[scope.tense]:settings.tenses;const out=[];for(const v of pool)for(const t of tenses)for(const p of settings.persons){if(t==='imperative'&&p==='1s')continue;const forms=v.forms[t]?.[p];if(forms?.length)out.push({key:`${v.id}|${t}|${p}`,verb:v,tense:t,person:p,accepted:forms})}return out}
export class QuestionDeck{constructor(items,weights={}){this.original=[...items];this.weights=weights;this.queue=[]}next(){if(!this.queue.length){this.queue=[...this.original];for(let i=this.queue.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[this.queue[i],this.queue[j]]=[this.queue[j],this.queue[i]]}const wrong=this.original.filter(x=>(this.weights[x.key]||0)>0);this.queue.push(...wrong.sort(()=>Math.random()-.5))}return this.queue.shift()}}
export function record(state,q,input,correct){const now=new Date().toISOString(), item={at:now,verbId:q.verb.id,infinitive:q.verb.infinitive,tense:q.tense,person:q.person,input,correct,answer:q.accepted[0]};state.history.push(item);if(state.history.length>1000)state.history.shift();state.stats[correct?'correct':'incorrect']++;for(const [bucket,key] of [[state.stats.byVerb,q.verb.id],[state.stats.byTense,q.tense]]){bucket[key]??={correct:0,incorrect:0,practiced:0};bucket[key].practiced++;bucket[key][correct?'correct':'incorrect']++}if(correct)delete state.pendingErrors[q.key];else state.pendingErrors[q.key]=(state.pendingErrors[q.key]||0)+1;return item}
