export const grammarSections=[
['persones','Persones gramaticals',`Les sis persones són <b>jo, tu, ell/ella/vostè, nosaltres, vosaltres</b> i <b>ells/elles/vostès</b>. El subjecte sovint es pot ometre perquè la terminació verbal ja indica la persona.`],
['conjugacions','Les tres conjugacions',`La primera conjugació acaba en <b>-ar</b> (parlar); la segona, en <b>-er</b> o <b>-re</b> (témer, perdre); i la tercera, en <b>-ir</b> (dormir). Alguns verbs de la tercera són incoatius: serveixo, serveixes…`],
['modes','Modes verbals',`L’<b>indicatiu</b> presenta fets; el <b>subjuntiu</b> expressa sovint desig, dubte o subordinació; el <b>condicional</b>, una situació hipotètica; i l’<b>imperatiu</b>, ordres o instruccions.`],
['indicatiu','Temps de l’indicatiu',`El present situa l’acció ara o com a habitual; l’imperfet descriu accions habituals o en curs en el passat; els passats presenten accions acabades; el futur situa l’acció després del moment de parla.`],
['subjuntiu','Temps del subjuntiu',`S’utilitza en contextos com <i>Vull que vinguis</i> o <i>Potser sigui tard</i>. Té present, imperfet i els temps compostos corresponents.`],
['conditional','Condicional',`Es forma, en general, amb l’infinitiu i les terminacions -ia, -ies, -ia, -íem, -íeu, -ien: <i>Ho faria demà</i> (Lo haría mañana).`],
['imperative','Imperatiu',`Serveix per donar ordres o consells: <i>Vine aviat!</i> (¡Ven pronto!). No té primera persona del singular. L’imperatiu negatiu es forma amb el subjuntiu: <i>No vinguis</i>.`],
['nonpersonal','Formes no personals',`L’infinitiu anomena el verb; el gerundi expressa una acció en desenvolupament; i el participi intervé en els temps compostos: <i>parlar, parlant, parlat</i>.`],
['compound','Temps compostos',`Es formen amb una forma d’<b>haver</b> i el participi: <i>Hem arribat</i> (Hemos llegado). El participi no concorda amb el subjecte en aquesta construcció.`],
['periphrasticPast','Passat perifràstic',`Es forma amb el present d’<b>anar</b> i l’infinitiu: <i>Vaig llegir el llibre</i> (Leí el libro). És molt habitual en català.`],
['irregulars','Verbs irregulars',`Verbs freqüents com <i>ser, haver, anar, fer, tenir, venir, poder</i> o <i>dir</i> canvien l’arrel o les terminacions. Convé aprendre’ls per famílies i practicar-ne les formes.`],
['orthography','Canvis ortogràfics',`Alguns canvis mantenen el so: c → qu (<i>toco/toqui</i>), g → gu (<i>pago/pagui</i>), ç → c (<i>començo/comenci</i>) i j → g davant e o i en determinats models.`],
['accents','Accentuació bàsica',`Els accents formen part de l’ortografia: <i>parlà</i> i <i>parla</i> no són la mateixa forma. Les agudes acabades en vocal, vocal+s, -en o -in solen dur accent; les planes, quan no acaben així.`]
];
export const EXAMPLES={present:['Expressa un fet actual o habitual.','Cada dia parlem català.','Cada día hablamos catalán.'],imperfect:['Descriu una acció habitual o en curs en el passat.','Abans vivíem aquí.','Antes vivíamos aquí.'],periphrasticPast:['Expressa una acció passada i acabada.','Ahir vam arribar tard.','Ayer llegamos tarde.'],simplePast:['Expressa una acció passada acabada, sobretot en registres formals.','Ell arribà al vespre.','Él llegó por la tarde.'],perfect:['Relaciona una acció passada amb el present.','Avui hem treballat molt.','Hoy hemos trabajado mucho.'],pluperfect:['Situa una acció abans d’una altra de passada.','Ja havíem sortit.','Ya habíamos salido.'],future:['Expressa una acció posterior.','Demà vindran.','Mañana vendrán.'],futurePerfect:['Presenta una acció acabada en un moment futur.','Demà ja haurem acabat.','Mañana ya habremos terminado.'],conditional:['Expressa una hipòtesi o cortesia.','Jo ho faria.','Yo lo haría.'],conditionalPerfect:['Expressa una hipòtesi passada no realitzada.','Ho hauríem fet.','Lo habríamos hecho.'],subjPresent:['Expressa desig, dubte o necessitat.','Vull que vinguis.','Quiero que vengas.'],subjImperfect:['Expressa una situació subordinada passada o hipotètica.','Volia que vinguessis.','Quería que vinieras.'],subjPerfect:['Expressa una acció acabada en un context de subjuntiu.','Espero que hagis arribat.','Espero que hayas llegado.'],subjPluperfect:['Expressa una acció anterior en un context passat o irreal.','Si haguessis vingut…','Si hubieras venido…'],imperative:['Dona una ordre, un consell o una instrucció.','Vine aviat!','¡Ven pronto!']};
