import test from'node:test';import assert from'node:assert/strict';import{normalizeAnswer,isCorrect,fold,filterVerbs,candidates,QuestionDeck,record}from'../js/engine.js';
const verb={id:'venir',infinitive:'venir',rank:1,irregular:true,forms:{present:{'3p':['venen']},imperative:{'2s':['vine']}}};
test('normalitza majúscules i espais però conserva accents',()=>{assert.equal(normalizeAnswer('  HAN   VINGUT '),'han vingut');assert.equal(isCorrect('parlara',['parlarà']),false)});
test('accepta variants completes',()=>{assert.equal(isCorrect('siguem',['siguem','sem']),true);assert.equal(isCorrect('han',['han vingut']),false)});
test('cerca sense accents i filtres',()=>{const vs=[{...verb,infinitive:'néixer',rank:2},{...verb,id:'parlar',infinitive:'parlar',rank:101,irregular:false}];assert.equal(fold('néixer'),'neixer');assert.equal(filterVerbs(vs,{search:'neixer',frequency:100}).length,1);assert.equal(filterVerbs(vs,{frequency:100,type:'regular'}).length,0)});
test('candidats respecten persones, temps i imperatiu',()=>{const state={favorites:[],pendingErrors:{}},settings={frequency:100,regular:true,irregular:true,favoritesOnly:false,errorsOnly:false,persons:['1s','2s','3p'],tenses:['present','imperative']};const x=candidates([verb],settings,state);assert.ok(x.some(q=>q.tense==='present'&&q.person==='3p'));assert.ok(!x.some(q=>q.tense==='imperative'&&q.person==='1s'))});
test('una sessió pot limitar-se a un únic temps',()=>{const state={favorites:[],pendingErrors:{}},settings={frequency:100,regular:true,irregular:true,favoritesOnly:false,errorsOnly:false,persons:['2s','3p'],tenses:['present','imperative']};const x=candidates([verb],settings,state,{tense:'imperative'});assert.ok(x.length>0);assert.ok(x.every(q=>q.tense==='imperative'))});
test('baralla sense repetir abans d’esgotar el paquet',()=>{const a=[1,2,3].map(key=>({key})),d=new QuestionDeck(a);assert.equal(new Set([d.next().key,d.next().key,d.next().key]).size,3)});
test('registra estadístiques i errors pendents',()=>{const s={history:[],stats:{correct:0,incorrect:0,byVerb:{},byTense:{}},pendingErrors:{}};const q={key:'venir|present|3p',verb,tense:'present',person:'3p',accepted:['venen']};record(s,q,'venen',true);record(s,q,'venan',false);assert.equal(s.stats.correct,1);assert.equal(s.stats.byVerb.venir.practiced,2);assert.equal(s.pendingErrors[q.key],1)});
